### ISSUE TITLE
About model optimization

### ISSUE THREAD

**Issue by remiMZ** [x-zho14/MAPLE#1]
Hi Xiao Zhou:

When I run cnn_mnist_probability_1step_irm.py, I found that theta and score functions are optimized along the training phase, but the model parameters, e.g. MLP, do not seem to be optimized?  

Looking forward to your reply!

**Comment by x-zho14** [comment]
What the goal of bilevel optimization is the learning of outer loop parameters, the optimization of inner loop parameters is just the tool to achieve this goal. The optimization of model parameters is in function train_to_converge.
